### ISSUE TITLE
[Question]: Is this getting upstreamed in 4.10 ?

### ISSUE THREAD

**Issue by victoredwardocallaghan** [ipts-linux-org/ipts-linux-new#1]
Pretty much what the title says..

**Comment by smartbeast** [comment]
It's hard to be in 4.10 since changes in i915 driver is too much IPTS specific. As a service provide, the  i915 driver should provide generic interface to use GPU though GuC. It means there should be well defined interface for clients to talk to GuC. We keep asking this but not sure it would be available for 4.10

**Comment by victoredwardocallaghan** [comment]
@smartbeast ok; i'm unfamiliar with intel as I normally work on amdgpu and mesa stuff..

I did not understand commit 63a894472 why does that binary need to exist? hexdump -C suggests its just a bunch of paths? Could you elaborate on that please?

**Comment by smartbeast** [comment]
It has "path"s as well as how to configure the binaries which can even be chained. for short, it has many useful information and I'm planning to add more. It can be ascii file but, due to boot speed, I decided to have it as binary which can be loaded and directly used as it is.
